### ISSUE TITLE
Need code sample for  tealium-react-native 1.0.10

### ISSUE THREAD

**Issue by syahrizan05** [Tealium/tealium-react-native#100]
Hi.
I need to temporarily use tealium-react-native 1.0.10.

Can anyone point me to tutorial or working code sample as the one sample i have found only for React Native 2

Thank you

**Comment by jameskeith** [comment]
@syahrizan05 - You can switch to any v1.X tags in Github to see the original sample application if you wish. For example, the latest [1.X.X tag is here](https://github.com/Tealium/tealium-react-native/tree/1.1.0) and you'll find the sample app under the `TealiumSampleApp` as mentioned in the original [v1.X documentation](https://docs.tealium.com/platforms/react-native-v1/install/)

Hopefully that helps for now, but let us know if you need anything else.

**Comment by syahrizan05** [comment]
thank you will try it out now
