### ISSUE TITLE
Is this supported?

### ISSUE THREAD

**Issue by fauna5** [Tealium/tealium-react-native#11]
A react native plugin does not appear on the list of Integrations on the Tealium website - https://community.tealiumiq.com/t5/tkb/communitypage if we use this project, will it be updated / tested for future Tealium releases? There are no releases on github - https://github.com/Tealium/tealium-react-native/releases 

Or is it, as i suspect, an example project that we should take the code from? the license file says "You agree that Tealium is under no obligation to provide You with support for the Software". However if we copy the code into our project then we run into the license issue - https://github.com/Tealium/tealium-react-native/issues/12

**Comment by craigrouse** [comment]
NPM package support has now been added. Please let us know if you require further information.
