### ISSUE TITLE
Cannot build iOS: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by vincent-paing** [Tealium/tealium-react-native#113]
I'm getting this following error when I build after updating to `2.2.0` version'

```
❌  ld: symbol(s) not found for architecture arm64
```

Going back to `2.1.3` version fixes this

**Comment by jameskeith** [comment]
Hi @vincent-paing - thanks for raising this.
Can I confirm that you have added the additional lines to your Podfile, as set out in the [release notes](https://github.com/Tealium/tealium-react-native/releases/tag/2.2.0)?
```
pod "tealium-react-native-swift", :path => '../node_modules/tealium-react-native/tealium-react-native-swift.podspec'
```

I don't believe this has made it to our main docs site just yet, but it will be there soon.

**Comment by vincent-paing** [comment]
Adding that fixes it, thanks you
