### ISSUE TITLE
License makes this software unusable

### ISSUE THREAD

**Issue by fauna5** [Tealium/tealium-react-native#12]
We cannot use this software. The license https://github.com/Tealium/tealium-react-native/blob/master/LICENSE.txt#L19 says "Tealium will retain all title, ownership, and Intellectual Property Rights in the Software and any derivative works thereof". This means that if we use the software in our app then Tealium will own all the IP.

If this software is supposed to be an example then please consider providing it with a less restrictive open source license such as the MIT license - https://opensource.org/licenses/MIT

**Comment by chrisanderberg** [comment]
@fauna5 We're discussing this internally and we'll get back to you with more details when we can.

**Comment by craigrouse** [comment]
Tealium is commercial software, and may not be compatible with all 3rd party or open source licenses. Closing this issue for now. If you require further assistance in this matter, please speak to your account manager. Thank you.
