### ISSUE TITLE
support for react native 0.68

### ISSUE THREAD

**Issue by nschild** [Tealium/tealium-react-native#136]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':tealium-react-native' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32

**Comment by jameskeith** [comment]
Hi @nschild - can I confirm which version of the `tealium-react-native` plugin you are using? as I recall we updated the gradle plugin version in use in one of the most recent releases specifically to support v0.68

**Comment by AlexanderEggers** [comment]
@nschild I had the same issue. It was related to tealium using Kotlin sources since 2.0.0. Because of that your root project has to define the kotlin gradle plugin. Have a look at this page for more details: https://developer.android.com/kotlin/add-kotlin
