### ISSUE TITLE
Crash within Tealium core android library for android users, Please update com.tealium:kotlin-core to 1.4.2

### ISSUE THREAD

**Issue by tamilselvantv** [Tealium/tealium-react-native#137]
Hi we noticed that there is a fix made on **tealium-kotlin** (1.4.2) for the app crashes. Please update the tealium-kotlin library to the latest version to avoid crash on android devices.

Attaching the link for the issue: https://github.com/Tealium/tealium-kotlin/issues/175

**Comment by tamilselvantv** [comment]
Any Update on this fixing tealium-kotlin library upgradation?

**Comment by jameskeith** [comment]
@tamilselvantv - my apologies for the slow reply on this.
I'll get a task raised internally to get the dependencies updated - we have new features from the later versions to add as well so hopefully shouldn't be too long.

**Comment by tamilselvantv** [comment]
@jameskeith Is there any update on library upgradation its causing lot of issues on android devices

**Comment by jameskeith** [comment]
Hi @tamilselvantv 
Thanks for your patience on this - its coming very soon. There is already a PR with the relevant changes, but it's waiting on one final update to be included. Hopefully the release should be this side of Christmas.

**Comment by tamilselvantv** [comment]
Is this issue fixed in 2.3.0?

**Comment by jameskeith** [comment]
Hi @tamilselvantv - yes, the v2.3.0 release includes the latest release of our kotlin sdk (1.5.1) which should therefore fix the crashes mentioned here.
