### ISSUE TITLE
Events not send

### ISSUE THREAD

**Issue by mustafakameldev** [Tealium/tealium-react-native#138]
I tried to use tealium version 1.0.10,

initialized the app like this:
` Tealium.initialize(
            'ACCOUNT',
            'PROFILE',
            'prod',
            null,
            null,
            'MAIN',
            true);
    }`
and added the events send the events like this:
` Tealium.trackView("ME EVENTS", { "TEST_EVENT": "TEST EVENT DATA" });`

but i got no connection between the app and tealium and events not send

**Comment by craigrouse** [comment]
@mustafakameldev Could I ask why you're using such an old release? Thank you.

**Comment by mustafakameldev** [comment]
I tried it but app not even start after install it,
i got some error such as 
`could not find com.tealium:library:5.7.0`
`Could not find com.tealium:kotlin-core:1.4.1`
and right now i got this error:
`* What went wrong:
Execution failed for task ':tealium-react-native:compileDebugKotlin'.
> Compilation error. See log for more details`

so i tried an old version and its worked, I'm using react-native v0.65.1

Thank you for your support

**Comment by jameskeith** [comment]
@mustafakameldev - those errors would be indicative of not having the required reference to our Maven repository as outlined in the documentation:
https://docs.tealium.com/platforms/react-native/install/#android
Have you added that to your project level build.gradle?

As a note, I would not expect to see both `com.tealium:library` and `com.tealium:kotlin-core` both being imported by our `tealium-react-native` integration. `tealium-react-native` v1.x will import the former, and v2.x will import the latter, but they both live on the same Maven repository mentioned above.

**Comment by mustafakameldev** [comment]
I had to update my package version 2
