### ISSUE TITLE
iOS simulator crash since version 2.2.0 when app reloads after code changes

### ISSUE THREAD

**Issue by hstorz** [Tealium/tealium-react-native#150]
Since version 2.2.0 of tealium-react-native, the iOS simulator crashes, when I make code changes and the app reloads. The app and the iOS simulator crashes and opens a "send  report to Apple" dialog. So I need to start the app again and Metro Bundler needs to load again after each change. The change can be a simple console.log
[crash.log](https://github.com/Tealium/tealium-react-native/files/11142903/crash.log)
. 

I now downgraded to 2.1.3 again with some changes to the build.gradle of Android since it was outdated and not compatible with current react-native 0.71.4 and everything is fine again. But to be able to update in the future it would be great if this could be fixed.

This problem still exists in 2.3.0.

I added a report of the native crash that I got from Flipper logs.

**Comment by craigrouse** [comment]
@hstorz thanks for reporting this. We'll take a look.

**Comment by trister1997** [comment]
Hey @hstorz! Thanks for the report. I am looking into this issue and I am having trouble reproducing. Could you attach a sample project that is having the issue? Also what version of node/npm (and yarn if your using yarn), and xcode are you using?

**Comment by craigrouse** [comment]
@hstorz Just checking if you were able to resolve this? Thanks!

**Comment by hstorz** [comment]
With the downgrade to 2.1.3 I don't have any issue. I tried again the 2.3.0 also on a new machine with M2 but still have the problem. After I launch the app in iOS simulator and I make a little change in my mobx store, the app fast refreshes and crashes immediately with the native error I attached already. When I comment out a property like visitorServiceEnabled in the initialize  method then the fast refresh starts to work. But as soon as I reopen the app the problem starts again. Even with the working property changes. So this is a strange behaviour. Unfortunately this is within a very large project and I don't have a small reproducable sample, yet.

**Comment by craigrouse** [comment]
@hstorz We're still looking into this. We have a mix of Apple silicon and Intel Macs on our team, and have so far only checked on Intel. We'll run a test on Apple Silicon too and see if we can reproduce the issue.

**Comment by hstorz** [comment]
@jameskeith Ok thanks for looking into the problem. Yes I added the podspec to my podfile as mentioned in the documentaion . But still had the problem.

**Comment by craigrouse** [comment]
@hstorz this has been open for quite some time, and we've been unable to reproduce the issue. Are you still experiencing the crash? If so, we'll be happy to take another look and see if we can fix it. Thanks.

**Comment by craigrouse** [comment]
Thanks @hstorz! Great to hear that it's resolved for you.
