### ISSUE TITLE
Android: trackEvent is calling trackView

### ISSUE THREAD

**Issue by ferrannp** [Tealium/tealium-react-native#16]
From https://github.com/Tealium/tealium-react-native/blob/master/android/TealiumModule.java#L171-L175

Isn't this a bug? Shouldn't it be `instance.trackEvent(...)` ?

**Comment by jonwong-tealium** [comment]
@ferrannp Thanks for pointing that out. We'll have that fixed.

**Comment by jonwong-tealium** [comment]
Hi @ferrannp . Thanks for bringing this to attention. This is fixed in the latest [tealium-react-native 1.0.2](https://www.npmjs.com/package/tealium-react-native) version.
