### ISSUE TITLE
Android Build issue with RN 0.71

### ISSUE THREAD

**Issue by Rackles** [Tealium/tealium-react-native#160]
When trying to build an android project I get the following error:

![tealium-react-native-build-issue](https://github.com/Tealium/tealium-react-native/assets/19647074/86653ae6-fcb4-4928-8f92-8b7eb0858853)

Used Versions:
- react-native: 0.71.13
- tealium-react-native: 2.3.1

Possible Solutions:
- Update version to a fitting one supporting RN 0.71 or even RN 0.72
- dynamically retrieving the kotlin version in order to allow it to be overwritten from the parent project. (An example would be like here: https://github.com/mrousavy/react-native-vision-camera/blob/4e96eb77e0755edf5a4351d61fa36d60415f1db6/package/android/build.gradle)

**Comment by jameskeith** [comment]
@Rackles Thanks for raising this with us.
I'll have this raised internally to get it addressed - incidentally, I don't see this issue when I build using a brand new RN app, but I can certainly see why it would potentially cause an issue.

**Comment by Rackles** [comment]
We are currently not using hermes with Android which might be a cause for this issue, but I'm not sure. This upgrade is on our agenda but we are not able to do this right now for different reasons. 

If this is something you decide to adjust I'm happy with it, otherwise I will check if an change to hermes might fix it on its own. 
Thanks for the quick response.

**Comment by AhmSaeed** [comment]
Any updates on this? I'm trying with React native 0.72.4 and Gradle 7.4.2

**Comment by craigrouse** [comment]
@AhmSaeed we're close to releasing this fix. Will confirm when it's ready.

**Comment by tamayok** [comment]
@AhmSaeed @Rackles This has been addressed in the latest release. Please check it out, and let us know if you have any other issues.
