### ISSUE TITLE
Session id has value after terminating Tealium instance in Android

### ISSUE THREAD

**Issue by DaliaElhefny** [Tealium/tealium-react-native#167]
tealium-react-native version: 2.3.2
Platfrom: Android

My case is that I initialize Tealium then get its sessionID value to make sure that it is initialized, then destroy tealium instance by calling `Tealium.terminateInstance()` and get the sessionID again to make sure that tealium instance is terminated.

Expected:
When getting the sessionID value after calling `Tealium.terminateInstance()` it should be `null` (same value as before initializing Tealium)

Actual:
When getting the sessionID value after calling `Tealium.terminateInstance()` it returns the same sessionID as before terminating tealium instance.

**Comment by craigrouse** [comment]
@DaliaElhefny calling terminateInstance is generally not expected during the lifecycle of an app, and would only be used in exceptional circumstances. This sounds like a very odd use case - can you enlighten us on what you're trying to do? It might be more appropriate to have our customer support team look into this with you - https://support.tealiumiq.com/. Thanks.

**Comment by DaliaElhefny** [comment]
@craigrouse I want to have the ability to enable and disable Tealium SDK during the same session of the app
EX: Having a toggle that starts Tealium SDK when on and stops it when off
I'm using `Tealium.initialize` and `Tealium.terminateInstance` to start and stop the SDK, and I want to check if Tealium SDK is enabled or disabled in my code to perform some logic, that's why I'm calling the session ID to know the status of Tealium but it doesn't reflect the status, do you have any other recommendation to know if tealium SDK is enabled or disabled programatically?

**Comment by craigrouse** [comment]
@DaliaElhefny we'll have a look into this for you and let you know.

**Comment by craigrouse** [comment]
@DaliaElhefny I think we've identified what's causing the issue. We'll update you here when we've fixed it and published a new release. I can't give you a definite timeframe, but we'll of course aim to get it done as soon as we can.

**Comment by jameskeith** [comment]
This should now be resolved in the [latest release 2.4.0](https://github.com/Tealium/tealium-react-native/releases/tag/2.4.0)
