### ISSUE TITLE
'cmath' file not found when compiling iOS on RN 0.60

### ISSUE THREAD

**Issue by joan-domingo** [Tealium/tealium-react-native#23]
Hi, I'm getting the following error when compiling Tealium in a react-native 0.60 project:
```
In file included from /Users/jdom/dev/other/AwesomeProject/node_modules/tealium-react-native/ios/TealiumModule/TealiumModule.m:3:
In file included from /Users/jdom/dev/other/AwesomeProject/ios/Pods/Headers/Public/React-Core/React/RCTConvert.h:17:
In file included from /Users/jdom/dev/other/AwesomeProject/ios/Pods/Headers/Private/yoga/Yoga.h:10:
/Users/jdom/dev/other/AwesomeProject/node_modules/tealium-react-native/ios/Pods/Folly/folly/portability/Math.h:19:10: fatal error
: 'cmath' file not found
#include <cmath>

         ^~~~~~~
1 error generated.


** BUILD FAILED **
```

## Steps to reproduce:
1- Create a new RN project with the current latest version 0.60 ```react-native init AwesomeProject```
2 - ```yarn add tealium-react-native```
3 - Add temporary podspec file in Tealium lib for react-native to support autolinking
4 - Add pod to podfile ```pod 'TealiumIOS', '~> 5.5.2'```
5 - ```pod install```
6 - Build iOS ```react-native run-ios```

I've got the same issue before on another project that was running RN 0.59.9 and I tried to upgrade it to 0.60. Any hint on how to fix this is appreciated.

Let me know if I can help or you have any questions about this.

**Comment by craigrouse** [comment]
@joan-domingo Could you see if the PR that @thymikee has kindly submitted resolves your issue? https://github.com/Tealium/tealium-react-native/pull/24

**Comment by thymikee** [comment]
@craigrouse this PR doesn't resolve it, I hit still hit it.

**Comment by joan-domingo** [comment]
@craigrouse what @thymikee said. The PR only adds autolink support, which I kind of already did in the step number 3.

**Comment by craigrouse** [comment]
@joan-domingo @thymikee Thank you. This appears to be an issue with Folly, which is a react native dependency. We'll see what we can do.

**Comment by thymikee** [comment]
FYI: https://github.com/facebook/react-native/issues/25349. This is likely gonna be fixed in 0.61, so for now I'd advise not to upgrade to RN 0.60 if you use a library with a framework.

**Comment by craigrouse** [comment]
@thymikee thanks for the update. If that's the case, we won't plan to spend any further time fixing this specific issue. Does that sound OK to you, or do you think there's still something we could do to mitigate the issue? We will leave the issue open in any case for visibility.

**Comment by joan-domingo** [comment]
That's fine for me, I'll let you how it goes know after 0.61 is out.

**Comment by hugo-chq** [comment]
Hi, we've reached the same issue with react-native 0.61 RC3.

**Comment by craigrouse** [comment]
@hugo-chq We are currently updating the plugin to fix another issue that was raised yesterday, so we'll be sure to test with 0.61 also and see if we can reproduce the issue. Watch this space for updates.

**Comment by lutakyn** [comment]
I have also faced this same issue
1. I created a temporary podspec file for auto linking
2. pod install TealiumIOS
3. cleaned build folder and run application.
4. build failed due to this same error.
5. if anyone has been able to by pass this problem,can he let us know what he did
6. also I want to know when Tealium will update their library.

**Comment by jameskeith** [comment]
1.0.7 has been released with autolinking support - tested with react native 0.61.2 and I cannot reproduce the issues listed here.
Can we retest this on the latest release?

**Comment by joan-domingo** [comment]
I tested the release 1.0.7 with react native 0.61.2 and looks good. I'm closing the issue.
