### ISSUE TITLE
Cannot find module "node ./node_modules/tealium-react-native/scripts/postlink.js"

### ISSUE THREAD

**Issue by jbristol-trav** [Tealium/tealium-react-native#27]
We are facing an issue when trying to install `tealium-react-native@1.0.6`:

```
warn Package tealium-react-native has been ignored because it contains invalid configuration. Reason: Cannot find module 'node ./node_modules/tealium-react-native/scripts/postlink.js'
```
 Taking a look at the most recent PR it looks like a typo in `npm-package/react-native.config.js`:

```javascript
commands: [require('node ./node_modules/tealium-react-native/scripts/postlink.js'),
               require('node ./node_modules/tealium-react-native/scripts/preunlink.js')]
```

Where the `node` command is in the require file path.

**Comment by craigrouse** [comment]
@jbristol-trav We're looking into this and will update you shortly. Thanks for letting us know.

**Comment by jbristol-trav** [comment]
I can get rid of the warning by modifying `node_modules/tealium-react-native/react-native.config.js` directly, i.e.

```javascript
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  commands: [
    require('./scripts/postlink.js'),
    require('./scripts/preunlink.js'),
  ],
};
```

However I receive another warning after doing this

`warn Package tealium-react-native has been ignored because it contains invalid configuration. Reason: "name" is required`

Reading the official [react native migration docs](https://github.com/react-native-community/cli/blob/master/docs/plugins.md#command-interface) for migration from rnpm it looks like we need the following:

```javascript
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  commands: [
    { name: 'postlink', func: () => require('./scripts/postlink.js') },
    { name: 'preunlink', func: () => require('./scripts/preunlink.js') },
  ],
};
```

Testing this locally seems to work

**Comment by jbristol-trav** [comment]
I have raised PR #28

**Comment by jameskeith** [comment]
this code has been removed for the latest release (1.0.7) as Autolinking takes care of this functionality - therefore it should no longer be causing any build errors if you update to the latest version.
Thanks for submitting a PR @jbristol-trav - but i'll close that off for now.

**Comment by jbristol-trav** [comment]
@jameskeith Thanks for the fix, will close this issue!
