### ISSUE TITLE
Tealium setup for ios with react native 0.60.0

### ISSUE THREAD

**Issue by jbristol-trav** [Tealium/tealium-react-native#29]
We are trying to setup `tealium-react-native@1.0.6` on our react native application running RN 0.60.0 and are facing linking issues in iOS.

We have performed the following:

1. 
```
yarn add tealium-react-native
react-native link
```
2. Dragged both TealiumIOS and TealiumIOSLifecycle to the Libraries folder and the linked libraries section in xcode.

Running a build we get `ld: framework not found TealiumIOSLifecycle`

I can resolve this by adding TealiumIOS and TealiumIOSLifecycle to our pod file, but this feels wrong if we have already manually linked them.

The documentation [mentions linking `libTealiumModule.a`](https://docs.tealium.com/platforms/react-native/install/#ios):

>Finally, under Libraries find TealiumModule.xcodeproj. Within, you will find a Products folder containing a libTealiumModule.a file.

Where exactly is the `TealiumModule.xcodeproj` file? Taking a look at both this project, the sample app, and tealium-ios we are unable to locate the module project file.

Opening the sample application included in this repo, xcode displays `libTealiumModule.a` as a "Recovered Reference" which indicates it is not located in the project tree.

Is this a clerical error in the documentation or are we missing something in our setup?

**Comment by jbristol-trav** [comment]
I am able to avoid the build error by manually adding both `TealiumModule.m` and `TealiumModule.h` to my project and importing the header file into our app delegate, however I am still not convinced since this is not documented. Is this a valid approach?

**Comment by lutakyn** [comment]
I will suggest tealium update their library for react native to auto link the project. As I see there is no .podspec file for iOS

**Comment by jonathanswong** [comment]
Hi @lutakyn , we are looking at updating Tealium for 0.60.0. Thanks.

**Comment by lutakyn** [comment]
Please do,I have not been able to integrate on iOS,I am even confused. The manual linking isn't working properly

**Comment by lutakyn** [comment]
@jonathanswong ,I raised an issue,please check it up for me,thank you

**Comment by jameskeith** [comment]
thanks for your patience all. 1.0.7 should take care of the autolinking support now. Let me know if you still have issues after updating.

**Comment by jbristol-trav** [comment]
@jameskeith Thanks for the update, we have a spiked out an upgrade to 1.0.7 and will provide an update here. If anyone else can confirm the fix before we do I can go ahead and close this.

**Comment by jbristol-trav** [comment]
We have confirmed this fix, will close this issue. Thanks again!
