### ISSUE TITLE
Maven (JAR) dependencies Tealium Error Message

### ISSUE THREAD

**Issue by techme33** [Tealium/tealium-react-native#31]
“Team, we are trying to use the tealium libraries in one of our Android projects. The build is run within a secured environment, where not all of the Public Maven repositories are accessible.

The build seems to fail while resolving the Maven (JAR) dependencies for the tealium.  Error message below

Searched in the following locations:
- http://internal nexus url/com/tealium/library/5.5.5/library-5.5.5.pom
- http://internal nexus url/com/tealium/library/5.5.5/library-5.5.5.jar

Required by:
   project: app > project : tealium-react-native
  > Could not find com.tealium:lifecycle:1.1.
  Searched in the following locations:
   - http://internal nexus url/com/tealium/library/5.5.5/library-5.5.5.pom
   - http://internal nexus url/com/tealium/library/5.5.5/library-5.5.5.jar 

Please suggest the actual public Maven repository, where these dependencies are available.

thanks in advance
Louis

**Comment by jameskeith** [comment]
Hi @techme33 

All of our Maven artefacts are hosted by us at the following address and are publicly available should you need to download them:
http://maven.tealiumiq.com/android/releases/

Let me know if you need anything else.
James

**Comment by jameskeith** [comment]
Hi @techme33 
We you able to get past your problem with the maven url provided?

thanks

**Comment by xyuka** [comment]
@jameskeith 
I cannot download the library too via the url you provided...

**Comment by jameskeith** [comment]
@xyuka - the URL provided is just for the top level directory of our Maven server for all our Android library releases; the one you would typically add to your gradle build files as described in our setup guide: https://docs.tealium.com/platforms/android-java/install/#maven

To access the specific version that @techme33 asked for, the URL would be:
http://maven.tealiumiq.com/android/releases/com/tealium/library/5.5.5/library-5.5.5.aar
http://maven.tealiumiq.com/android/releases/com/tealium/library/5.5.5/library-5.5.5.pom
And there should also be `.md5` and `.sha1` files alongside both.

For reference though, the latest release at present is v5.6.1 and is available here
http://maven.tealiumiq.com/android/releases/com/tealium/library/5.6.1/library-5.6.1.aar
http://maven.tealiumiq.com/android/releases/com/tealium/library/5.6.1/library-5.6.1.pom

**Comment by christinasund** [comment]
Hi @xyuka, checking in to see if your issue/question was resolved by the comments above?

**Comment by christinasund** [comment]
@xyuka and @techme33 Closing this issue for now, but feel free to reopen if necessary. Thanks!

**Comment by thibmaek** [comment]
For anyone revisiting this ticket be sure to disable any adblocker on DNS level since they will block the maven URL as well via the wildcard *.tealiumhq.com in blocklists (e.g AdGuard or Pihole)
