### ISSUE TITLE
Setup on react-native 0.60.4,iOS failing 

### ISSUE THREAD

**Issue by lutakyn** [Tealium/tealium-react-native#32]
Environment 
react-native version 0.60.4
tealium-react-native version 1.0.6

This is the process I used
1. installed tealium-react-native
2. opened my projects .workspace file for iOS
3. dragged TealiumIOS.framework and TealiumIOSLifecycle.framework from the DeviceOnly folder  to Library folder in Xcode,for production purposes. I could not auto link it because I could't find .podspec file in the node modules of the tealium library
4. Added the 2 files to Embedded Binaries
5. Cleaned the build folder and rebuilt the project
6. The error I found was "null is not an object (evaluating 'tealium.module.intialize')" ,this has been stressful and I need a better outlined integration process

**Comment by jameskeith** [comment]
@lutakyn 
Thank you for your patience with this issue. There has now been a new release (v1.0.7) made available here and on `npm` that should include the support for Autolinking in 0.60+ - documentation on our portal soon to follow.
You should no longer need to drag any frameworks, or add them as embedded binaries as the newer React scripts should add the pod dependencies automatically.

please let us know how you get on.

**Comment by lutakyn** [comment]
After reinstalling tealium-react-native 1.0.7, this is the error I got below.
Please tell me the process to make tealium run on iOS successfully,
In XCode,deployment target is set to 11,
What is the maximum deployment target because it was not stated in the error.

```
CocoaPods could not find compatible versions for pod "TealiumIOS":
  In Podfile:
    TealiumIOS

    tealium-react-native (from `../node_modules/tealium-react-native`) was resolved to 1.0.7, which depends on
      TealiumIOS (= 5.6.3)

Specs satisfying the `TealiumIOS, TealiumIOS (= 5.6.3)` dependency were found, but they required a higher minimum deployment target.
```
This is the process I used:
1. installed tealium-react-native
2. cd ios && pod install
3. i also setup platform :ios, '11.0' in podfile

react-native 0.60.4

**Comment by jameskeith** [comment]
@lutakyn 
The podspec for tealium-react-native should require iOS 9.0 and above, and the podspec for the underlying TealiumIOS library is 8.0, so neither should have a problem with a minimum deployment target of 11.0.
I've just setup a test app with RN 0.60.4 and not had any issues importing the tealium-react-native package. Is it possible to share your Podfile/podfile.lock? if not, perhaps we can take this up through our support team.

**Comment by lutakyn** [comment]
after running pod update,my iOS project built successfully.I'm closing this issue.Thank you for your support.
