### ISSUE TITLE
React-Native UUID

### ISSUE THREAD

**Issue by spylefkaditis** [Tealium/tealium-react-native#33]
Does this library support retrieving a users UUID for iOS and Android?

**Comment by jameskeith** [comment]
Hi @spylefkaditis 

The `uuid` generated by the Tealium SDK is stored in our PersistentData. There are methods to retrieve both volatile and persistent data sources, so something like this should work:
```
Tealium.getPersistentDataForInstanceName("<your instance name>", "uuid", function(value) {
          var uuid = value;
          console.log("persistent uuid: " + uuid);
        });
```

**Comment by jameskeith** [comment]
@spylefkaditis - there has just been a new release of this package (v1.0.7) that also fixes the method signature for `Tealium.getPersistentData()` so you don't need to specify the instance name if you are just using the default instance.

Did you have any luck with the code provided?

**Comment by jameskeith** [comment]
@spylefkaditis - hopefully the above solution resolved your issue, I'm closing this issue down as we've not heard from you. 
Let us know if you are still having a problem retrieving the uuid
