### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by jbristol-trav** [Tealium/tealium-react-native#41]
I have gone ahead and created [typings](https://gist.github.com/jbristol-trav/40ce04f0aeb346d9f2855657c8788d09) for this library that we are using locally. These cover our use cases, but we would prefer to not have to maintain them. Is it possible to get these added in the next release?

A note about these typings: I have not tested these exhaustively, it might be useful to verify them

**Comment by jonathanswong** [comment]
Hi @jbristol-trav . Thank you for your contribution! We'll take a look at these and try to get it in the next release.

**Comment by christinasund** [comment]
Hi @jbristol-trav, the typings you provided were included in our [latest release](https://github.com/Tealium/tealium-react-native/releases/tag/1.0.8). Thank you, again, for your contribution! Closing this issue for now, but let us know if anything else comes up.
