### ISSUE TITLE
index.d.ts warnings on export default static

### ISSUE THREAD

**Issue by francescodrag** [Tealium/tealium-react-native#48]
When compiled with tsc watch the project has 6 warnings referred to index.d.ts
Please, can u fix it?
Best regards

**Comment by craigrouse** [comment]
@francescodrag could you please be more explicit about exactly which problems you're seeing? If you could also please give us the exact commands you're running, and the versions of each of your build tools, that would help (tsc-watch version, React Native version). We're not very familiar with tsc-watch, so the more information you can give us, the better. Thank you.

**Comment by francescodrag** [comment]
Hi Craig, thank u for the response.
So, this is a version list of my build tools:
React-native: 0.60.5;
tealium-react-native: 1.0.8;

The problem is on index.d.ts file, as u can see from the attachment, Typescript give errors when u try to define more than one default method, so.. to suppress the warning u should remove the ‘default' declaration from the static method (initialize(), initializeWithConsentManager() and initializeCustom()) ‘cause it’s useless.

Thank u in advance,
Francesco Dragone.

[cid:4ED01029-D9F6-4FA5-9FFA-A1201CFA55B3]

On 21 Feb 2020, at 10:34, Craig Rouse <notifications@github.com<mailto:notifications@github.com>> wrote:


@francescodrag<https://github.com/francescodrag> could you please be more explicit about exactly which problems you're seeing? If you could also please give us the exact commands you're running, and the versions of each of your build tools, that would help (tsc-watch version, React Native version). We're not very familiar with tsc-watch, so the more information you can give us, the better. Thank you.

**Comment by craigrouse** [comment]
Perfect - thank you @francescodrag. We'll get onto this as soon as we can.

**Comment by craigrouse** [comment]
@francescodrag this is now fixed in v 1.0.9 (the TS changes are the only changes in that version). Please check and confirm it works for you. Thank you.

**Comment by francescodrag** [comment]
It’s works fine, thank u very much for the support!

Have a good  day,
Francesco Dragone.

On 24 Feb 2020, at 11:45, Craig Rouse <notifications@github.com<mailto:notifications@github.com>> wrote:


@francescodrag<https://github.com/francescodrag> this is now fixed in v 1.0.9 (the TS changes are the only changes in that version). Please check and confirm it works for you. Thank you.

**Comment by craigrouse** [comment]
Thanks very much @francescodrag. You're most welcome. Thank you for taking the time to report it and suggest a fix.
