### ISSUE TITLE
tealium-react-native@2.0.0 is incomplete

### ISSUE THREAD

**Issue by thibmaek** [Tealium/tealium-react-native#65]
Downloading this module from NPM will break an install because common.js is missing from the package. This renders documentation at `https://docs.tealium.com/platforms/react-native/install/#javascript` useless

## Steps to reproduce

1. `npm pack tealium-react-native` to download the tarball for 2.0.0 from NPM
2. `tar xzvf tealium-react-native-2.0.0.tgz` to unpack
3. `ls package` will list the extracted tarball and show the common.js file is missing

**Comment by christinasund** [comment]
@thibmaek We apologize for the inconvenience here. We just released version [2.0.1](https://github.com/Tealium/tealium-react-native/releases/tag/2.0.1) which contains the fix for the missing `.ts` file. Let us know if this does not resolve the problem, or else feel free to close the issue. Thanks!

**Comment by christinasund** [comment]
@thibmaek Closing this for now, but let us know if you do not feel this is resolved. Thanks again!
