### ISSUE TITLE
File missing from dependency 

### ISSUE THREAD

**Issue by florind12** [Tealium/tealium-react-native#67]
As per provided docs at https://docs.tealium.com/platforms/react-native/. 
Following constants are required to be imported from `tealium-react-native/common `.
`import { TealiumConfig, TealiumView, TealiumEvent, ConsentCategories, Dispatchers, Collectors, ConsentPolicy, Expiry, ConsentExpiry, TimeUnit, ConsentStatus, TealiumEnvironment } from 'tealium-react-native/common';`

comms.ts file is missing. 

The current API Reference doesn't seem to be supported by the last up to date dependency.
Eg: addData() is not available. instead, we can use the deprecated one setPersistentData. 

package.json
`"tealium-react-native": "^2.0.0",
 "react-native": "~0.63.3"
`   

android/build.gradle
`allprojects {
    repositories {
        mavenLocal()
        maven {
            url "https://maven.tealiumiq.com/android/releases/"
        }
`
android/app/build.gradle
`dependencies {
    implementation 'com.tealium:library:5.8.0'`
    

Also, I've been trying this: 

const tealiumConfig = {
  account: "test",
  profile: "main",
  environment: ["dev", "qa", "prod"],
};

Tealium.initialize(tealiumConfig);

And I get the following error: 
`TypeError: _tealiumReactNative.default.initialize is not a function. (In '_tealiumReactNative.default.initialize(tealiumConfig)', '_tealiumReactNative.default.initialize' is undefined)
`
Am I missing something?
Thanks.

**Comment by craigrouse** [comment]
@florind12 I believe this is related to this issue, which I see you're watching: https://github.com/Tealium/tealium-react-native/issues/65

We have a fix prepared and will post here when it's released. Thanks for your patience and sorry for the inconvenience.

**Comment by christinasund** [comment]
@florind12 Thank you for raising this and we apologize if this is holding you up. We just released version [2.0.1](https://github.com/Tealium/tealium-react-native/releases/tag/2.0.1) which contains the fix for the missing `.ts` file. Let us know if this does not resolve the problem, or else feel free to close the issue. Thanks!

**Comment by florind12** [comment]
There is still a small issue on pod install. 
`
[!] A license was specified in podspec `tealium-react-native` but the file does not exist - myproject/node_modules/tealium-react-native/LICENSE.txt
[!] Unable to read the license file `LICENSE.txt` for the spec `tealium-react-native (2.0.1)`
[!] Unable to read the license file `LICENSE.txt` for the spec `tealium-react-native (2.0.1)`
`

**Comment by craigrouse** [comment]
Thanks for letting us know @florind12. I believe this is just a warning, and doesn't prevent you using the plugin? Nevertheless, we'll get it corrected.

**Comment by florind12** [comment]
While on Android, I succeed in having it functional, on iOS I encounter this error at the build phase. 

`
defined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumWrapper.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactNative-799e0b73b0ac6aadbe01fa4ef78ab7822150c16738a7ee215ce625b5a0ae5276.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(EventEmitter.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactConstants.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactExtensions.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_TealiumSwift in libtealium-swift.a(LegacyConsentConfiguration.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_TealiumSwift in libtealium-swift.a(RemoteCommandsManager.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_TealiumSwift, __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by craigrouse** [comment]
@florind12 It seems like this issue has shown up on other SDKs too: https://github.com/facebook/react-native-fbsdk/issues/755

Can you try the workaround of manually creating a Swift file in your xcode project, and accepting the prompt to create a bridging header?

**Comment by florind12** [comment]
That seems to fix this issue.
Ty
