### ISSUE TITLE
Unable to initialise Remote Commands

### ISSUE THREAD

**Issue by shannon-voda** [Tealium/tealium-react-native#68]
Receiving error everytime Tealium attempts to initialise when adding Dispatchers.RemtoeCommands as shown below

```
  static initialize(account, profile, isDev, dataSource) {
    const config: TealiumConfig = {
      account,
      profile,
      dataSource,
      environment: isDev ? TealiumEnvironment.dev : TealiumEnvironment.prod,
      dispatchers: [Dispatchers.Collect, Dispatchers.TagManagement, Dispatchers.RemoteCommands],
      collectors: [Collectors.AppData, Collectors.DeviceData, Collectors.Lifecycle, Collectors.Connectivity],
    }
    Tealium.initialize(config)
  }
```

```
`TealiumReactNative.RemoteCommandEvent` is not a supported event type for TealiumReactNative. Supported events are: ``

-[RCTEventEmitter addListener:]
    RCTEventEmitter.m:95
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread
```

Enviroment
"tealium-react-native": "^2.0.1",
"react": "17.0.1",
"react-native": "0.63.4",
Device: iOS Simulator 12.4

**Comment by jameskeith** [comment]
Hi @shannon-voda 
Thanks for raising this issue - I've not been able to replicate it locally yet I'm afraid. The example app in this repo does make use of `Dispatchers.RemoteCommands` so it should work as expected.
Can you try cleaning your pods and reinstalling?
```
rm -r node_modules/
yarn install

cd ios && pod cache clean --all && pod install && cd ..
```
And then restart your metro bundler and app.

**Comment by florind12** [comment]
I experience the same issue. 
Steps to replicate: 
1.Open the app.
2. Open React Native Debug menu.
3. Tap Reload 

Expected: 
The app reloads and everyone is happy.

Actual:
The app crashes and returns the following error: 
`TealiumReactNative.RemoteCommandEvent` is not a supported event type for TealiumReactNative. Supported events are: ``

Worth mentioning that if you manually close the app and reopen it, works just fine. The only issue is when the app gets reloaded.

**Comment by jameskeith** [comment]
Thanks for the information @florind12
I can reproduce this issue after a Reload, so will take a look at why this is happening.

**Comment by christinasund** [comment]
@shannon-voda and @florind12 We have just released a [new version](https://github.com/Tealium/tealium-react-native/releases/tag/2.0.2) that includes the fix for the error. Please let us know if you are still seeing issues. Thanks!

**Comment by shannon-voda** [comment]
looks like its all working now. Thanks!
