### ISSUE TITLE
TealiumWrapper is undefined

### ISSUE THREAD

**Issue by anhvoduy** [Tealium/tealium-react-native#77]
at `static initialize(config) {
        TealiumWrapper.initialize(config);
        ...................
}` => TealiumWrapper is undefined

**Comment by christinasund** [comment]
@anhvoduy Thank you for reaching out with this! We are looking into this and will keep you updated. Thanks again

**Comment by anhvoduy** [comment]
@christinasund For android, it's work fine after I reconfigure suitable gradle version, thanks for your response.

**Comment by christinasund** [comment]
Closing this, for now, let us know if you encounter any more issues.
