### ISSUE TITLE
Create NPM repo

### ISSUE THREAD

**Issue by frankenthumbs** [Tealium/tealium-react-native#9]
hey y'all,

Will you be creating an NPM repo so we don't have to copy pasta files like animals? it would be nice if the ios folder had a `.podspec`/`.xcodeproj` and the android folder had a `build.gradle` file.

**Comment by tamayok** [comment]
@frankenthumbs The sample app should have the `.podspec/.xcodeproj` and the `build.gradle`. We're working on getting the NPM repo up and running.

**Comment by frankenthumbs** [comment]
@tamayok those look like they are for the examples themselves and not the project.

**Comment by chrisanderberg** [comment]
@frankenthumbs Yes, the xcodeproj and build.gradle files are specific to the sample app. As mentioned above, we're working on the NPM package.

**Comment by MartinDoyleUK** [comment]
What update on this, please? We're very keen to implement this, as we have a "sister project" who are using the Tealium web library, and we need something we can rely on, version-wise, which an npm publish would achieve.

**Comment by chrisanderberg** [comment]
@MartinDoyleUK Development of the npm package is still in progress, and is nearing completion. We should have more specific information soon.

**Comment by craigrouse** [comment]
@frankenthumbs @MartinDoyleUK We just released the NPM package. http://npmjs.org/tealium-react-native. Let us know how you get on.
