### ISSUE TITLE
Tealium incompatible with RN 0.64 (and Hermes?)

### ISSUE THREAD

**Issue by thibmaek** [Tealium/tealium-react-native#90]
After setting up Tealium RN v2 according to the documentation on the Tealium docs website my application will no longer build:

![image](https://user-images.githubusercontent.com/6213695/121029737-26d7a800-c7a9-11eb-8d3e-f3a3360a1886.png)

- Pods are installed and linked
- Hermes is enabled
- `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` is set to YES
- Created a Swift file `File.swift` and bridging header in my projects top level folder

For now I reverted back to Tealium RN v1, but would like to upgrade as soon as possible.

**Comment by christinasund** [comment]
@thibmaek Thanks for bringing this to us. We are currently looking into it for you and will keep you updated.

**Comment by christinasund** [comment]
@thibmaek We have added support for Hermes in the [2.2.1 release](https://github.com/Tealium/tealium-react-native/releases/tag/2.1.1). Let us know if this resolves the errors you were seeing.

**Comment by thibmaek** [comment]
Good! Will try this out ASAP

**Comment by thibmaek** [comment]
Hey @christinasund , just tried out the latest version but this is throwing errors against the new Swift code in tealium-react-native:

```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libtealium-swift.a(TealiumAppDelegateProxy.o)
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumWrapper.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactNative-0a879017c3758defd8590e4c9a8126b9f26197a3817c9f654006ff4b9af233ad.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(EventEmitter.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(RemoteCommandFactory.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactConstants.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native in libtealium-react-native.a(TealiumReactExtensions.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_TealiumSwift in libtealium-swift.a(LegacyConsentConfiguration.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_TealiumSwift, __swift_FORCE_LOAD_$_swiftWebKit_$_tealium_react_native )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lostchopstik** [comment]
I may be having a related issue with my project, wasn't sure it was something that should be a new issue or not.

I'm currently on v2.1.1 and having a similar error:
```
Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libtealium-swift.a(TealiumAppDelegateProxy.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Everything is working great on the Android side...

**Comment by jameskeith** [comment]
thank you both for flagging this - after an initial look at the error, this seems to be a fairly common problem relating to XCode 12.5 - the suggested workarounds seem pretty inconsistent, so we'll take a look at our end and get back to you.

**Comment by lostchopstik** [comment]
@jameskeith Thanks for looking into it. Is there any kind of timeline we can expect for potential fixes?

**Comment by jameskeith** [comment]
I've been testing this at our end on a brand new RN 0.64 test application and was able to reproduce two issues here upon building in XCode 12.5.1
The first of which was mentioned in @thibmaek's stack trace,
```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
```
This resolved itself after adding a bridging header to the app in XCode by simply creating a new swift file in the project.

For the second issue listed in @lostchopstik's report (and @thibmaek's) required me to remove the following from the library search paths for the project as described here on a similar React Native issue report (step 3 in the link provided) 
https://github.com/facebook/react-native/issues/31179#issuecomment-829536845

After that, everything builds and runs as expected - can I recommend that you try this and let me know how you get on?

**Comment by lostchopstik** [comment]
Hey @jameskeith, I'm not quite sure if this is what did it for me but when I tried again with the new 2.1.2 release, iOS has built perfectly fine ever since.

**Comment by jameskeith** [comment]
ok thanks @lostchopstik - glad to hear that it's building as expected now.
