### ISSUE TITLE
TealiumSwift/TealiumSwift-Swift.h file not found

### ISSUE THREAD

**Issue by KirilVelichkov** [Tealium/tealium-react-native#98]
I have updated my **tealium-react-native** to **2.1.3**
After trying to build my app for iOS i get the following error **TealiumSwift/TealiumSwift-Swift.h file not found**
The error is inside the file - **ios/Pods/tealium-swift/tealium/core/objc/TealiumDelegateProxy+Swizzle.m**

Here is some information about my versions.
"react-native": "0.66.1",
Swift -  5.3.2
xCode - 12.3

It looks like the **TealiumSwift/TealiumSwift-Swift.h** is never created. 

Has anyone faced a similar issue and do you have any advices on a solution?

**Comment by KirilVelichkov** [comment]
@jameskeith Do you have any thoughts on the above?

**Comment by KirilVelichkov** [comment]
Ok I`ve realised the issue is not in this package, but in tealium-swift and found that there is already an issue created about it.
https://github.com/Tealium/tealium-swift/issues/239

Sorry for the alarm.

**Comment by craigrouse** [comment]
@KirilVelichkov We believe the issue you're seeing is different to the other one. Could you please try upgrading your Xcode version to at least 12.5.1, or preferably 13.1?

**Comment by KirilVelichkov** [comment]
@craigrouse I am pretty sure my issues is the same as https://github.com/Tealium/tealium-swift/issues/239. The only difference is that i am not doing any changes to my Podfile. The error that i get is exactly the same as the screenshot provided in https://github.com/Tealium/tealium-swift/issues/239. 

From what I've read in order to import a swift file inside objc file we need a bridging header file and **s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }** set in the podfile of the library and I couldn't find these in the tealium-swift repo.
So my best guess is that may be this is causing the issue for me. 

I will try upgrading xCode tonight (since it takes ages to do) and will write back tomorrow if that fixed the issue, but please give me your thoughts on the point above.

**Comment by craigrouse** [comment]
@KirilVelichkov thanks for your reply. The thing is that it works perfectly on a standard Xcode project without RN, and we've tested on Xcode 12.5.1 and 13.1, so we can only assume it's an issue with RN. We will attempt to reproduce the issue in RN also. Let us know if upgrading Xcode makes any difference.

**Comment by KirilVelichkov** [comment]
@craigrouse I have update my xCode to 13.1 and the issue is still there. 
Please let me know if you find a solution.

**Comment by craigrouse** [comment]
Thanks for confirming @KirilVelichkov. We're looking into it.

**Comment by Enricoza** [comment]
@KirilVelichkov We released a new version of the TealiumSwift library (`2.5.1`) fixing this issue. 
You should be able to use the new version without changing the podfile as tealium-react-native already uses the latest version. 

I'm closing for now but feel free to reopen in case something else arises.
